ALTER TABLE performance_snapshots
    ADD COLUMN IF NOT EXISTS form_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last5_goals INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last5_assists INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last5_rating DOUBLE PRECISION NOT NULL DEFAULT 0;
